// Code generated by protoc-gen-go.
// source: CookieData.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	CookieData.proto

It has these top-level messages:
	Cookie
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type Cookie struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	AuthVersion      *int64 `protobuf:"varint,2,req,name=auth_version" json:"auth_version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Cookie) Reset()         { *m = Cookie{} }
func (m *Cookie) String() string { return proto1.CompactTextString(m) }
func (*Cookie) ProtoMessage()    {}

func (m *Cookie) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Cookie) GetAuthVersion() int64 {
	if m != nil && m.AuthVersion != nil {
		return *m.AuthVersion
	}
	return 0
}

func init() {
}
